const yearEl = document.getElementById('year'); if (yearEl) yearEl.textContent = new Date().getFullYear();
const btnSignup = document.getElementById('btnSignup'); const btnLogin  = document.getElementById('btnLogin'); const btnPlay   = document.getElementById('btnPlay'); const accountHint = document.getElementById('accountHint');
const modal = document.getElementById('authModal'); const closeBtn = modal.querySelector('.close'); const form = document.getElementById('authForm'); const modalTitle = document.getElementById('modalTitle');
function openModal(mode){ modal.classList.remove('hidden'); modal.setAttribute('aria-hidden','false'); modalTitle.textContent = mode === 'login' ? 'Log In' : 'Create Account'; form.dataset.mode = mode; }
function closeModal(){ modal.classList.add('hidden'); modal.setAttribute('aria-hidden','true'); }
btnSignup.addEventListener('click', ()=>openModal('signup')); btnLogin.addEventListener('click', ()=>openModal('login')); closeBtn.addEventListener('click', closeModal); modal.addEventListener('click', (e)=>{ if(e.target===modal) closeModal(); });
const Session = { isAuthed(){ return !!localStorage.getItem('idleChaosToken'); }, async signup(email, password){ localStorage.setItem('idleChaosUser', JSON.stringify({email})); localStorage.setItem('idleChaosToken', 'dev-token-' + btoa(email).slice(0,12)); return true; }, async login(email, password){ localStorage.setItem('idleChaosUser', JSON.stringify({email})); localStorage.setItem('idleChaosToken', 'dev-token-' + btoa(email).slice(0,12)); return true; }, logout(){ localStorage.removeItem('idleChaosUser'); localStorage.removeItem('idleChaosToken'); } };
function refreshUI(){ const authed = Session.isAuthed(); btnPlay.disabled = !authed; accountHint.style.display = authed ? 'none' : 'block'; btnLogin.textContent = authed ? 'Log Out' : 'Log In'; } refreshUI();
btnLogin.addEventListener('click', (e)=>{ if(Session.isAuthed()){ Session.logout(); refreshUI(); } else { openModal('login'); } });
form.addEventListener('submit', async (e)=>{ e.preventDefault(); const fd = new FormData(form); const email = fd.get('email'), password = fd.get('password'); const mode = form.dataset.mode || 'signup'; try{ if(mode==='signup') await Session.signup(email, password); else await Session.login(email, password); closeModal(); refreshUI(); document.getElementById('btnPlay').focus(); }catch(err){ alert('Something went wrong. Replace with real API.'); console.error(err); } });
btnPlay.addEventListener('click', ()=>{ if(!Session.isAuthed()) return; window.open('play/index.html', '_blank', 'noopener'); });